# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Where fun leads to charity
email: funpluscharity@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Where fun leads to charity
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://volleyballleague.github.io" # the base hostname & protocol for your site
twitter_username: yaravind
github_username:  volleyballleague

# Build settings
markdown: kramdown
